### ISSUE TITLE
How to use with individual routes?

### ISSUE THREAD

**Issue by jaredreich** [koa-modules/multer#10]
Not understanding how this can be done with koa-multer...

```js
const multer = require('koa-multer')

const multerMiddleware = multer({ dest: './.uploads/' })

router.post('/files', multerMiddleware, function (next) {
  console.log(this.req.files) // undefined
  console.log(this.request.files) // undefined
  ...
})

**Comment by fundon** [comment]
If you use koa v1 and koa-multer v0.x then see https://github.com/koa-modules/multer/blob/v0.x/test/form.js.

Else if use koa v2 and koa-multer v1 then see https://github.com/koa-modules/multer/tree/master/test.

**Comment by jaredreich** [comment]
Sorry but I'm not seeing the explanation... the only relevance is:

```js
var app2 = koa();
app2.use(multer({
  includeEmptyFields: true
}));
app2.use(router2.routes());
```

which does not describe individual routes.

Thanks very much for your help.

**Comment by fundon** [comment]
Do you use koa v1 and koa-multer v0.x?

**Comment by fundon** [comment]
```
router.post('/files', multerMiddleware, function (next) {
  console.log(this.req.files) // undefined
  console.log(this.request.files) // undefined
  ...
})
```

Should:

```
router.post('/files', multerMiddleware, function * (next) {
  console.log(this.req.files) // undefined
  console.log(this.request.files) // undefined
  ...
})
```

**Comment by jaredreich** [comment]
Thank you kindly for the help.

Great work on Koa!

**Comment by mezod** [comment]
I understand you were using koa v1 and koa-multer v0.x right?

**Comment by fundon** [comment]
@mezod Yes

**Comment by mezod** [comment]
thanks, I had to end up using koa-router-multer as koa-multer is not compatible with koa-router apparently :(
