### ISSUE TITLE
multer is writing to `ctx.req` instead of `ctx.request`

### ISSUE THREAD

**Issue by FWeinb** [koa-modules/multer#14]
I think multer should write to `ctx.request` because that is the  [koa request object](https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxrequest) currently it is writing to the `ctx.req` which is the original node request object.

In my opinion this change would align the behaviour of this module with the koa ecosystem.

**Comment by danegigi** [comment]
I agree 100%

What I did right now is use `koa-compose` to combined the multer middlware and a simple middleware that copies `ctx.req.files`, `ctx.req.body`, & `ctx.req.file` to `ctx.request`. I know this is not the best way to do it but I can live with it until this is fixed.

**Comment by QianSu** [comment]
Upload pictures are binary data, how can I convert the picture file?

**Comment by dominhhai** [comment]
@QianSu Did you try to change the file extension?

**Comment by QianSu** [comment]
@dominhhai Brother, thank you for your advice, I have solved this problem

**Comment by raphaelsoul** [comment]
on my side, those below are always `undefined`:
* `ctx.request.files` 
* `ctx.request.file`
* `ctx.req.file`
* `ctx.req.files`

the configuration like this:
```
import multer from 'koa-multer'
import bodyparser from 'koa-bodyparser'
const upload = multer({ dest: '/path/to/tmp' })

//use it globally
app.use(multer.any())
app.use(bodyparser())
```
I tried postman and html form with `enctype="multipart/form-data"`, both had saved file with hashed name but can't I access to file infomation via `ctx`

the version is `koa-multer@1.0.1` and `koa@2.2.0`.

Weired

**Comment by magicdawn** [comment]
Since pass ctx.req, ctx.next to an express middleware is kind of Hack. Why not delegate 
`ctx.req.body` / `ctx.req.file` / `ctx.req.files` to `ctx.request` but not the reverse 😂

**Comment by techborn** [comment]
I have made a pull request that simply exposes the respective objects to Koa's Request wrapper. #15 

Side note: I have tried changing this middleware to pass the ctx.request object to multer, but that failed due to the fact that multer uses the streaming properties (eg: [`req.pipe(busboy)`](https://github.com/expressjs/multer/blob/c45e4b0aad6a8ab5ff3ad6c2fb30f9497e3f2392/lib/make-middleware.js#L176)) of the native Request object, whereas the Koa wrapper doesn't seem to have that exposed.

**Comment by i5ting** [comment]
@fundon can be merge that pr?

**Comment by niftylettuce** [comment]
Please see my comment at https://github.com/koa-modules/multer/issues/30#issuecomment-506837638 and close this issue.  The official Koa organization has forked this repository and released it (with PR's merged) under `@koajs/multer`.  Thank you.
