### ISSUE TITLE
Why parsed body not available on Koa's supercharged request?

### ISSUE THREAD

**Issue by eightyfive** [koa-modules/multer#2]
I was wondering why the parsed body is not made available to Koa's `this.request`.

Using the package I could only find `body` attached to `this.req`.

I know this follows closely [express/multer](https://github.com/expressjs/multer), but this is somehow confusing when using with Koa. All Koa's middlewares tend to attach additional work to `this.request` instead of `this.req` (actually koa itself is built following that philosophy).

Let me know. Cheers.

**Comment by coderhaoxin** [comment]
reasonable, +1

**Comment by eightyfive** [comment]
Would you accept a pull-request? I can try something.

**Comment by coderhaoxin** [comment]
PR welcome, cc @fundon

**Comment by fundon** [comment]
@eightyfive +1, welcome

**Comment by eightyfive** [comment]
Would you also consider a Documentation update mentioning that [koa-multer](https://github.com/koa-modules/multer) is useful to parse normal HTML forms sent over as [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData)?

Or would this be best suited in [expressjs/multer](https://github.com/expressjs/multer) docs?

Anyhow there is no mention of that in either docs and I had kind of a hard time figuring it out (used all sorts of full-blown `bodyparser` before...)...

Regarding that very pull-request, we should definitely mention that body is now available on `this.request.body`.

What do you think?

**Comment by eightyfive** [comment]
https://github.com/koa-modules/multer/pull/3

**Comment by fundon** [comment]
Yes, need more details.
BTW, currently just use [expressjs/multer](https://github.com/expressjs/multer)-v**0.x**(<1.0).

**Comment by eightyfive** [comment]
Ping me if you need help with docs.

**Comment by fundon** [comment]
@eightyfive thanks, please if you want. :smiley: 

And I started a new branch [koa-v2_multer-v1](https://github.com/koa-modules/multer/tree/koa-v2_multer-v1).

**Comment by fundon** [comment]
@eightyfive  Laned in 0.0.2.
