### ISSUE TITLE
Access to stream underneath

### ISSUE THREAD

**Issue by batrudinych** [koa-modules/multer#28]
Hi, I may have missed something. Is there any way to access file data with streams? I can see two options only: download to the disk straightforward or store in memory as a buffer.

**Comment by niftylettuce** [comment]
Please see my comment at https://github.com/koa-modules/multer/issues/30#issuecomment-506837638 and close this issue.  The official Koa organization has forked this repository and released it (with PR's merged) under `@koajs/multer`.  Thank you.
