### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by niftylettuce** [koa-modules/multer#30]
If I am granted npm/GitHub access, here are my plans for 2.0.0 release:

- [x] expose `ctx.file`, `ctx.files`, `ctx.request.file`, and `ctx.request.files` versus binding to the Node request object (https://github.com/koa-modules/multer/pull/23)
- [x] add multer as a peer dependency so streams can be used (https://github.com/koa-modules/multer/pull/23

**Comment by niftylettuce** [comment]
cc @LinusU @niftylettuce

**Comment by niftylettuce** [comment]
I have forked this repo to @koajs/multer

<https://github.com/koajs/multer>

2.0.0 release to come soon.

**Comment by niftylettuce** [comment]
I have released an official @koajs fork of this package at https://github.com/koajs/multer with latest version being `v2.0.0`.  Note that the only breaking changes are that `ctx.req.file` and `ctx.req.files` are no longer accessible.  Please use `ctx.file`, `ctx.files`, or `ctx.request.file` and `ctx.request.files` instead.

Here is a list of the issues it resolves:
- https://github.com/koa-modules/multer/issues/30
- https://github.com/koa-modules/multer/issues/14
- https://github.com/koa-modules/multer/issues/26
- https://github.com/koa-modules/multer/issues/28
- https://github.com/koa-modules/multer/issues/27
- https://github.com/koa-modules/multer/issues/29

I suggest to @fundon that he archive this repository, publish a deprecation notice `npm deprecate koa-multer "Please use @koa/multer instead, see <https://github.com/koajs/multer>"`, and update the `README.md` file with a notice as well with the same deprecation message.

Thank you.

**Comment by LinusU** [comment]
Nice 👏 👏

**Comment by fundon** [comment]
@niftylettuce I published, Thanks.

**Comment by niftylettuce** [comment]
@fundon Fantastic.  I truly appreciate this.  Thank you so much, this will be very helpful for community and future of Koa!

![Screen Shot 2019-08-29 at 3 46 29 PM](https://user-images.githubusercontent.com/523141/63975272-3d00f200-ca74-11e9-912e-58814c019bf3.png)
