### ISSUE TITLE
Trying out the example gives an error

### ISSUE THREAD

**Issue by fazlerabby07** [koa-modules/multer#6]
I am using Koa v1.1.2

My code is:
```javascript
import koa from 'koa';
import bodyParser from 'koa-bodyparser';
import multer from 'koa-multer';
import {port} from './global_config';
import cors from 'kcors';
import {securedRoute, publicRoute} from './app/route';

const app = koa();
app.use(cors());
app.use(bodyParser());
app.use(publicRoute.routes());
app.use(publicRoute.allowedMethods());
app.use(securedRoute.routes());
app.use(securedRoute.allowedMethods());

app.use(multer({ dest: './uploads/'}));

// Start server
app.listen(port || 3000);
```

Error in cmd:
<img width="960" alt="screen shot 2016-03-06 at 1 40 59 am" src="https://cloud.githubusercontent.com/assets/3228768/13549981/e5c6df3a-e33c-11e5-89c5-7c744a52446c.png">

What should I do?

My second question is: what will be the **koa-multer** version of this original multer's code:
```javascript
app.post('/photos/upload', upload.array('photos', 12), function (req, res, next) {
  // req.files is array of `photos` files 
  // req.body will contain the text fields, if there were any 
})
```
I mean, I need unique multer configs for each uploading routes in the project.

Please help!!!

**Comment by fundon** [comment]
@fazlerabby07 Is it fixed?

**Comment by oleole90** [comment]
On behalf of my teammate @fazlerabby07, YES!
We were using the latest version of koa-multer with koa v1.1.2, which is not compatible as mentioned in the Readme. So we followed [this](https://github.com/koa-modules/multer#0x-working-with-multer-v0xv018-is-the-latset-version-of-v0x-and-koa-v1x) and that solved our problem.

(However, multer-v0.x is not enough for us so we'll be migrating to KOA v2-alpha soon.
If you @fundon have any advice, please feel free to let us know.)

**Comment by fundon** [comment]
@oleole90 Ok, great!

Koa v2 is great that I can highly recommended. :)

**Comment by oleole90** [comment]
Thanks! :+1:
